version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: ojp-client-image
    container_name: ojp-client-container
    ports:
      - "3000:3000"
    # volumes:
    #   - .:/app
    tty: true