services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: ojp-client-image
    container_name: ojp-client-container
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    tty: true